### ISSUE TITLE
Gestures too sensitive, request parameter

### ISSUE THREAD

**Issue by AfromD** [SDraw/driver_leap#14]
Thank you for this driver, works quite well with my valve index!

I do have an issue though, that I am constantly triggering gestures when holding my hands in a comfortable pose. I need to spastically stretch my fingers to prevent gestures from triggering.

Could there be a configurable parameter, that slows down gesture recognition? Maybe some kind of dead zone, where any bends of fingers are not interpreted?

**Comment by SDraw** [comment]
Slowing down gesture recognition seems to be not possible because it's strictly connected with fingers data (direction, bending, angles beetween different fingers). Using configurable parameter for this can lead to gestures never reach full or zero recognition value.  
Dead zone sounds like a good solution, but current structure of CGestureMatcher doesn't have any access to configuration data.

**Comment by OFWModz** [comment]
I'd like to see something like this too.

**Comment by PickRelated** [comment]
@SDraw any way to tweak ON/OFF gesture latch? For example:
1. Thumbpress > 0.9 - Latch ON
2. Thumbpress < 0.2 - Latch OFF
It seems to me that currently we get something like `> 0.5 = ON`, `< 0.5 = OFF`. This causes a lot of triggering noise.

I hope you get my point.
